[package]
name = "ppc750cl-macros"
version = "0.1.0"
edition = "2018"
authors = ["Richard Patel <me@terorie.dev>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.28"
syn = { version = "1.0.74", features = ["full"] }
